version: "3.9"

services:
  postgres:
    container_name: lookinlab-db
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: /data/postgres
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres:/data/postgres
    ports:
      - "${DB_PORT}:5432"
    restart: unless-stopped

  app:
    container_name: lookinlab-app
    build:
      context: . 
      dockerfile: Dockerfile  
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT} 
    ports:
      - "${API_PORT}:8080" 
    depends_on:
      - postgres 
    restart: unless-stopped

volumes:
  postgres:
